### ISSUE TITLE
should iscsid.service use Type=simple and --foreground rather than Type=forking

### ISSUE THREAD

**Issue by smoser** [open-iscsi/open-iscsi#130]
The [etc/systemd/iscsid.service](https://github.com/open-iscsi/open-iscsi/blob/master/etc/systemd/iscsid.service) currently does `Type=forking` and uses `PIDFile` .  That path lead to weird behavior that I fixed in pull request [127](https://github.com/open-iscsi/open-iscsi/pull/127).

Does it make sense to just use `--foreground` and `Type=simple`.  That just makes the process tracking easier for systemd.

For more information https://bbs.archlinux.org/viewtopic.php?id=191669

**Comment by smoser** [comment]
I spoke with @xnox and he suggested that with socket activation in place, --foreground makes good sense.  Without the socket activation, then most ideally we'd still want to sdnotify somehow when the socket is available.

**Comment by gonzoleeman** [comment]
For SUSE we actually use socket activation and this stanza in the service file:

```
[Service]
Type=simple
ExecStart=/sbin/iscsid -f
KillMode=mixed

```

**Comment by gonzoleeman** [comment]
I think this is a hard issue to fully "close". Each distro does the service slightly differently. To "fix" this correctly, perhaps we should start with comparing notes, i.e. share how each distro does it. Perhaps we can then see if consensus is even possible, and if so work towards it.

**Comment by gonzoleeman** [comment]
We are upstream, and I believe the two systemd files, in etc/systemd are 6 years old. I would not garuntee that anyone uses those exact versions.

I know I do not put my SUSE systemd files here because SUSE and RedHat do this differently. And if we put up example or actual systemd files for SUSE and RedHat, shouldn't we really put them up for every distribution that's different?

I'm open to suggestion on how you'd like to proceed? I can point you at the public repository for SUSE open-iscsi, where you can easily peruse how we're doing it. See [SUSE open-iscsi at github](https://github.com/hreinecke/open-iscsi). We actually use 5 service files: Two for iscsid (iscsid.socket and iscsid.service), two for iscsiuio (likewise socket-activated), and one for iscsi sessions (iscsi.service).

Maybe one "solution", at least for now, is to add a README in etc/systemd that says that the unit files there are only examples?

**Comment by gonzoleeman** [comment]
Note: I believe I get where you are coming from. If SUSE and/or RedHat has figured out a good way of setting up the service, that knowledge should be shared so that other people/distros don't have to figure it out themselves.

**Comment by gonzoleeman** [comment]
See Issue #140 as I believe I will soon submit a pull request for iscsid to use sd_notify() to tell systemd when it's up and running. This will help in a couple of ways, but it will also mean that the iscsid.service unit file should be updated to use Type=notify and NotifyAccess=main.

**Comment by gonzoleeman** [comment]
Please see pull request #143 and issue #140, now fixed. I think this _may_ close this issue?

**Comment by xnox** [comment]
This is nice. @smoser we also need to contribute the udev rules / SYSTEMD_WANTS thing too, no?

**Comment by smoser** [comment]
Probably yes. 

For others, Dimitri is referring to 
https://bugs.launchpad.net/ubuntu/+source/curtin/+bug/1807978

Ubuntu now installs a udev tiles file seen here
https://git.launchpad.net/ubuntu/+source/open-iscsi/tree/debian/iscsi-disk.rules

**Comment by gonzoleeman** [comment]
Marking as closed.
