### ISSUE TITLE
How to debug the scsi command request?

### ISSUE THREAD

**Issue by zjs1224522500** [open-iscsi/open-iscsi#209]
I used `mkfs.ext4` to make filesystem on a raw device which is communicated by iscsi.
And the `mkfs.ext4` shows the error messgae such as:
```
Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information:    
Warning, had trouble writing out superblocks.
```
I guess the reason is the timeout of iscsi command execute. Because when error happened, the iscsi server end is still reading/writing disks.
Howerver, I have no clues to verify the guess.

Is there any ways to trace the iscsi command requests such as log files?

**Comment by zjs1224522500** [comment]
And I changed the timeout config `node.session.timeo.replacement_timeout` to a large value, but it seems like no effect.

**Comment by gonzoleeman** [comment]
Out of curiosity about your timeouts, what back end are you using? It's surprising it would be that slow. How large is the target disc?

Why did you think the replacement_timeout would help? This is the timeout used for creating a new session when one has failed.

Have you run iscsid in debug mode? If not, edit your systemd file that starts iscsid to add "-d9" (debug level 9) to the command line and restart. You can also pass "-d9" into the iscsiadm command, but that would will likely be less helpful, as you'll see lots of sysfs stuff and not much else (since iscsid does much of the work).

At least with debugging output we should be able to see what is timeout out.

Can I assume you have nops off? (You should.)

**Comment by gonzoleeman** [comment]
Is this still an issue?
