### ISSUE TITLE
Why the loginall mode in iscsi service mismatch with default startup mode defined in iscsid.conf

### ISSUE THREAD

**Issue by wenchao-hao** [open-iscsi/open-iscsi#232]
Here is my question: Why the loginall mode in iscsi service mismatch with default startup mode defined in iscsid.conf

Since the default mode is manual defined in iscsid.conf, then the nodes discovered by: iscsiadm -m discovery -t st -p xxxx
has node.startup set to be manual.

While iscsi.service specify loginall==automatic which mismatch with manual.

The two default mode do not match cause iscsi service can not login nodes automaticly when system reboot, administrator must
modify these configure after install open-iscsi to avoid this issue.

**Comment by gonzoleeman** [comment]
On Nov 12, 2020, at 10:59 PM, Wenchao Hao <notifications@github.com> wrote:
> 
> 
> Here is my question: Why the loginall mode in iscsi service mismatch with default startup mode defined in iscsid.conf
> 
> Since the default mode is manual defined in iscsid.conf, then the nodes discovered by: iscsiadm -m discovery -t st -p xxxx
> has node.startup set to be manual.
> 
> While iscsi.service specify loginall==automatic which mismatch with manual.
> 
> The two default mode do not match cause iscsi service can not login nodes automaticly when system reboot, administrator must
> modify these configure after install open-iscsi to avoid this issue.
> 
> 


The defaults are set up to try to best match the expectations of most people. But they can be modified, and usually should be modified by the administrator on each system to best match actual practice.

In other words, you can change the default from “manual” to “automatic”. But we do not set it up to do that by default, since that might surprise some people.

The README that comes with iscsi talks about this in section 7.3.

So you can:

1. Change the default to automatic (and restart iscsi), which changes all future connections to be automatic, or
2. Modify the value of “startup” for each target you actually want to be logged into automatically

Saying this one other way, not everyone wants every target to be logged into automatically any time you discover it. It’s up to you to decide.
— 
Lee Duncan

**Comment by wenchao-hao** [comment]
Got it, thanks a lot
