### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by hujkis** [open-iscsi/open-iscsi#242]
@gonzoleeman   
Hey Lee,  

I'm trying to get up to speed with iscsi testing and saw You've done some work on getting tests here working.  
To prevent duplication of work, I wanted to sync on the plans/direction/requirements for tests here.   

We've done some work on python-based libs, framework with [libsan](https://gitlab.com/rh-kernel-stqe/python-libsan) and [stqe](https://gitlab.com/rh-kernel-stqe/python-stqe) a while back (It is quite RHEL/Fedora-centric). We also came with the same conclusion as you, that fio would be suitable tool for IO testing. 

If one would write new tests using libsan, I wonder what would it take for them to be accepted here. 

This, I think, is close to what the original regression.sh did: https://gitlab.com/rh-kernel-stqe/python-stqe/-/blob/master/tests/iscsi/iscsi_params.py 

Regards
Martin

**Comment by gonzoleeman** [comment]
I appreciate your suggestion. Since the tests are only used against the source base, i.e. not delivered as part of the open-iscsi RPMs, it might be possible, even though libsan is not available on some other distributions (like mine).

What value do you think such tests would bring, as opposed to the python test suite, which is already there? In other words, what testing could you add that you couldn't add using the current framework?

**Comment by hujkis** [comment]
> libsan is not available on some other distributions (like mine).  

It should be distribution-agnostic, though I don't think anybody ever tested it. (eg. [pypi](https://pypi.org/project/libsan/))

> what testing could you add that you couldn't add using the current framework? 

Not sure, really. I was thinking things like target operations, but perhaps it's best not to mix non-initiator-related stuff here.

In any case, I've opened this to get up-to-speed and learn about open-iscsi project's plans for the tests. Maybe I'm missing something, but it seems like there isn't much in the *test* directory currently, ergo I though talking about different framework is not out of place.

**Comment by gonzoleeman** [comment]
Since the testing code is orthogonal to the functioning code, and it is not part of the released open-iscsi RPMs AFAIK, I see no reason to disallow this. Of course you'll need to (1) get it working, and (2) get at least a few tests working, then (3) submit a pull request. If it's preliminary, tag your request with RFC.

**Comment by hujkis** [comment]
Understood.
Thank You for your comments.
