### ISSUE TITLE
inactive (dead)

### ISSUE THREAD

**Issue by iomari** [open-iscsi/open-iscsi#256]
Greetings, I have 13 machines in a cluster and all have iscsi running. On all the machines except 3, iscsi status shows 'inactive (dead)'. All the machines have the same configuration. Any ideas as to why most of them show iscsi as inactive (dead)?

**Comment by gonzoleeman** [comment]
No idea, as you didn't supply enough information for me to be able to diagnose anything.

What distribution are you using? (Fedora seems like a common answer.) What version of that OS? What version of open-iscsi?

Please include the output of "systemctl status -l <your-service>". Or even "journalctl -x -e"? Generally when systemd marks a service as failed the output of "status" shows log messages about what failed.

You say you have "isscsi running" on 13 machines. I assume you mean open-iscsi, since "iscsi" is a protocol. In that case, why are you running open-iscsi on those nodes? Do they all point at different targets , the same targets, or no targets?

Have you tried running iscsid (the open-iscsi initiator daemon) in debug mode? If not, try adding "-d4" to the iscsid command line in your systemd unit file. (Or course reboot or reload systemd units after that.)

**Comment by gonzoleeman** [comment]
No reply, so closing this issue. Please re-open or open a new one, if needed.
