### ISSUE TITLE
A possible deadlock issue

### ISSUE THREAD

**Issue by ryancaicse** [open-iscsi/open-iscsi#326]
It seems that lock `nic->nic_mutex` is not released before Line 1029. Should it be a bug?
https://github.com/open-iscsi/open-iscsi/blob/095f59ca464220eae285de6b5f2ee31185a6a84c/iscsiuio/src/unix/nic_utils.c#L1015-L1029

Maybe a better way to fix it  is

```
		rc = pthread_cond_timedwait(&nic->nic_loop_started_cond,
					    &nic->nic_mutex, &ts);

		LOG_INFO("Created nic thread: %s", nic->log_name);
	}

	

error:
        pthread_mutex_unlock(&nic->nic_mutex);
	return;
}
```

**Comment by gonzoleeman** [comment]
This is (obviously) error-handling code that is generally never ran, since the whole thing is anti-functional if we cannot create a thread -- likely because there is no more memory?

Still, cleaning this up sounds good to me. And yes, it looks like the mutex should be released.

Please feel free to submit a pull request. If you do, I'll do my best to get the Marvell folks to review it, too, since they authored and generally maintain this code.

Note: there are a couple of other issues in iscsiuio, namely the compiler complaining about taking the address of members of a packed structure, that would be great to get resolved (if you're feeling spunky).

**Comment by ryancaicse** [comment]
I created a PR and please check it. Thanks!
