### ISSUE TITLE
RFC: Is it time to update our build system to automatically configure itself for diferent platforms (e.g. autotools, meson, etc)

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#359]
I have been getting tired of tweaking the build system each time there's a new library, executable, or platform with problems.

I was thinking of just biting the bullet and learning autotools (autoconf, automake, etc). The "iscsiuio" subdirectory of open-iscsi already uses "autoreconf"/"configure" (autotools), so it wouldn't be much of a stretch.

But I have been told that folks are moving away from autotools (and cmake) to meson. Sounds interesting. I'm reading up on meson.

Does anyone have any preferences/suggestions/ideas?

I have started playing with autotools in the "usr" subdirectory. I could push that branch, if anyone wants to look at it or play with it.

Okay, let the flood of great ideas begin!

**Comment by gonzoleeman** [comment]
I'm thinking nobody else cares ... until I change it and break everybody's build work flow.

**Comment by gonzoleeman** [comment]
I got feedback from a co-worker that suggested using meson instead of autoconf. I spent about a week converting open-iscsi **and** iscsiuio to use meson. I'm quite impressed.

Does anyone want to play with or try the code?

**Comment by eli-schwartz** [comment]
Looking at https://github.com/open-iscsi/open-iscsi/compare/use-meson-v1

I notice in a bunch of places you use `configure_file(..., copy: true, install: true, install_dir: 'some-directory'`

I think you can probably just use install_data for this? No need to copy static files around just to install them (but it does make sense for the template files).

Note also that configure_file having a copy-only mode is a bit of a hack, its main point is to actually replace templated information, and it has the somewhat unfortunate downside of performing a full buildsystem reconfigure if the input changes, since it needs to run at configure time. For the pure copy case, we just added a build-time function that doesn't reconfigure (but you need the unreleased Meson 0.64.0 from git master for that): https://mesonbuild.com/Release-notes-for-0-64-0.html#fscopyfile-to-replace-configure_filecopy-true

The `pthread_dep` stuff should probably use `dependency('threads')`? That uses `-pthread` in most places (`-lpthread` is generally not recommended, as it doesn't do some of the magic needed).

**Comment by gonzoleeman** [comment]
> Looking at https://github.com/open-iscsi/open-iscsi/compare/use-meson-v1

Thank you for your time and feedback!

> 
> I notice in a bunch of places you use `configure_file(..., copy: true, install: true, install_dir: 'some-directory'`
> 
> I think you can probably just use install_data for this? No need to copy static files around just to install them (but it does make sense for the template files).

Good call. I wish there was an "install_script()" call, for installing FILE.sh -> FILE. But install_data() works well enough! Thanks!

> 
> Note also that configure_file having a copy-only mode is a bit of a hack, its main point is to actually replace templated information, and it has the somewhat unfortunate downside of performing a full buildsystem reconfigure if the input changes, since it needs to run at configure time. For the pure copy case, we just added a build-time function that doesn't reconfigure (but you need the unreleased Meson 0.64.0 from git master for that): https://mesonbuild.com/Release-notes-for-0-64-0.html#fscopyfile-to-replace-configure_filecopy-true

I'm trying to avoid newer features, since I want open-iscsi to build even on older systems (as long as they have meson/ninja).

> 
> The `pthread_dep` stuff should probably use `dependency('threads')`? That uses `-pthread` in most places (`-lpthread` is generally not recommended, as it doesn't do some of the magic needed).

Again, good call!

I pushed these fixes and a few other cleanups (like updating the README file), so please check again if you get a chance.

**Comment by eli-schwartz** [comment]
> Good call. I wish there was an "install_script()" call, for installing FILE.sh -> FILE. But install_data() works well enough! Thanks!

Yeah, I'm not sure how much call there is for a new function based on this, considering it's ultimately not hard. I haven't really encountered the problem myself before, since I usually just name the scripts without extensions, but maybe that's just me...

Of course, there's a fair number of projects that seem to intentionally keep the extensions, my /usr/bin has a whole bunch of `*.sh` and `*.py` files so who even knows. :/

> I'm trying to avoid newer features

I would especially avoid unreleased features. :D The reason I mention this one is to point out that the current state of the art has suboptimal behavior and we would like to fix that.

Of course this does not matter if you decide you don't need to copy them at all. I think the main use of copying at build time will anyways be headers that need to be in a specific directory structure (we hit this problem a few times with subproject wraps, e.g. the project has `include/bar.h` in tree, but at install time it's `includedir/foo/bar.h` and you have to use `#include <foo/bar.h>` -- to make it work uninstalled, you need to emulate the install structure).

The upcoming copyfile method will, in the long term, allow handling this so that header changes are applied at buildtime.

**Comment by eli-schwartz** [comment]
Some other things I noticed:

```
conf.set('SBINDIR', sbin_dir)
```

sbin_dir can be a relative path (e.g. prefix "/usr", sbindir "sbin" -> "/usr/sbin"). This is fine for using it as an install_dir kwarg, as those treat relative locations as relative to prefix, but when configuring a string into a configuration_data, you should probably set it to `join_paths(get_option('prefix'), get_option('sbindir')`.

Incidentally, you don't need Meson < 0.49.0 support so you can use the syntactic sugar of `x / y` instead of `join_paths(x, y)`.

```
if current_meson_version.version_compare('>= 0.63.0')
  newer_meson_version = true
else
  newer_meson_version = false
endif
```

```
if <bool-condition>
    var = true
else
    var = false
endif
```

You can just do `var = <bool-condition>`.

```
if not fs.is_absolute(home_dir)
  home_dir = join_paths(get_option('sysconfdir'), home_dir)
endif
```

join_paths(absolute_a, absolute_b) will produce absolute_b.

```
c_args = get_option('c_args')
```

I'm not entirely sure why you're tracking this... isn't the point of c_args that it already applies to all targets? It's the flag equivalent  of the `$CFLAGS` environment variable.

genl_cargs -- this applies to all targets? You can use them via `add_project_arguments(genl_cargs, language: 'c')` and they'll be added to all targets without manually passing them in as `c_args: genl_cargs` to each one.

iscsi_doc_man_pages_static_arr seems to be just plain source files, that can be installed with `install_man(v)` instead of `install_data(v, install_dir: man_dir_8)`. It could also probably be a list instead of a key-value array. Note that install_man (and install_data) can take a list of sources, as long as you don't need separate kwargs for each source.

**Comment by gonzoleeman** [comment]
On Sep 1, 2022, at 12:23 PM, Eli Schwartz ***@***.***> wrote:
> 
> 
> Some other things I noticed:
> 
> conf.set('SBINDIR', sbin_dir)
> sbin_dir can be a relative path (e.g. prefix "/usr", sbindir "sbin" -> "/usr/sbin"). This is fine for using it as an install_dir kwarg, as those treat relative locations as relative to prefix, but when configuring a string into a configuration_data, you should probably set it to join_paths(get_option('prefix'), get_option('sbindir').
> 
> 
I’m trying to work around this convention in meson. :)

I want sbindir to be “/usr/sbin” (i.e. the default, assuming prefix=/usr), or “/sbin”. On SUSE, SLES uses “/sbin”, which ignore the prefix.

So if the user passes in an absolute path, i.e. “fred”, it should become prefix/fred. But if they pass in an absolute path, i.e. ‘/abc/fred”, I want it in ‘/abc/fred’, not prefix/abc/fred.
> Incidentally, you don't need Meson < 0.49.0 support so you can use the syntactic sugar of x / y instead of join_paths(x, y).
> 
> 

Cool.

> if current_meson_version.version_compare('>= 0.63.0')
>   newer_meson_version = true
> else
>   newer_meson_version = false
> endif
> if <bool-condition>
>     var = true
> else
>     var = false
> endif
> You can just do var = <bool-condition>.
> 
Yes, of course. :)
> if not fs.is_absolute(home_dir)
>   home_dir = join_paths(get_option('sysconfdir'), home_dir)
> endif
> join_paths(absolute_a, absolute_b) will produce absolute_b.
> 
> c_args = get_option('c_args')
> I'm not entirely sure why you're tracking this... isn't the point of c_args that it already applies to all targets? It's the flag equivalent of the $CFLAGS environment variable.
> 
I didn’t realize that. Cool.
> genl_cargs -- this applies to all targets? You can use them via add_project_arguments(genl_cargs, language: 'c') and they'll be added to all targets without manually passing them in as c_args: genl_cargs to each one.
> 
> 

No, some of the compiles use different args.
> iscsi_doc_man_pages_static_arr seems to be just plain source files, that can be installed with install_man(v) instead of install_data(v, install_dir: man_dir_8). It could also probably be a list instead of a key-value array. Note that install_man (and install_data) can take a list of sources, as long as you don't need separate kwargs for each source.
> 

Yes, I cleaned that up now. That was left over from when I was using copy_file().

Thanks again for your reviews! I owe you a beer. Keep it up if you have the time. :)

Also, I’ve received one suggestion to leave the old build system in place, in parallel, but I don’t like that idea. What do you think?

— 
Lee D

**Comment by eli-schwartz** [comment]
> I want sbindir to be “/usr/sbin” (i.e. the default, assuming prefix=/usr), or “/sbin”. On SUSE, SLES uses “/sbin”, which ignore the prefix.

Either you need to add a custom option not named "sbindir", or systems which use /sbin can use a version of Meson that fixed the design bug which forbade `--prefix=/usr --sbindir=/sbin`.

If they try to do this on older versions of Meson, Meson errors out because sbindir isn't inside the prefix.
If they pass `--sbindir=sbin` then it's interpreted as `/usr/sbin`.

You can also see how e.g. openrc worked around this: https://github.com/OpenRC/openrc/blob/master/meson.build#L92

They have a "rootprefix" option which they use instead of "prefix" for installing files that should be installed to / instead of /usr on systems with a split /usr.

> Also, I’ve received one suggestion to leave the old build system in place, in parallel, but I don’t like that idea. What do you think?

This is not a bad idea. There are plenty of projects that do this. However, there's a caveat to the notion.

Having multiple build systems for the sake of having multiple build systems is awkward, a support burden, fragments support efforts, and generally negates any advantages of switching from one to the other. You don't want to do this.

(Aside: for projects that primarily provide a library, it's also sometimes desirable to provide multiple build systems if those build systems make it easy to add the library as a submodule dependency to another project. It *is* a support burden, but it might be a worthwhile one. Also: autotools doesn't have that use case.)

What you probably *do* want to do, is have one major release after the new build system is introduced, where the old build system is still available, but is deprecated. It might print a warning if you use it, or require passing a configure flag such as --i-cant-use-meson-yet, or just be advised against in the README.

The idea is that when doing a complex port, you hope it all turns out well, and you give consumers a chance to try it out, but just in case specific consumers hit edge cases that cause issues, people can still use the old build system while those bugs are fixed, and at the same time they get valuable bug fixes from the new release. After the transition period of one release cycle is complete, you delete the old build system and declare victory.

**Comment by gonzoleeman** [comment]
> > I want sbindir to be “/usr/sbin” (i.e. the default, assuming prefix=/usr), or “/sbin”. On SUSE, SLES uses “/sbin”, which ignore the prefix.
> 
> Either you need to add a custom option not named "sbindir", or systems which use /sbin can use a version of Meson that fixed the design bug which forbade `--prefix=/usr --sbindir=/sbin`.
> 
> If they try to do this on older versions of Meson, Meson errors out because sbindir isn't inside the prefix. If they pass `--sbindir=sbin` then it's interpreted as `/usr/sbin`.
> 
> You can also see how e.g. openrc worked around this: https://github.com/OpenRC/openrc/blob/master/meson.build#L92
> 
> They have a "rootprefix" option which they use instead of "prefix" for installing files that should be installed to / instead of /usr on systems with a split /usr.

Yes, that seems fine for them, but I just want to move sbindir. My solution is simpler: in older releases, after building with meson/ninja, I just do "mv $DESTDIR/sbin $DESTDIR/usr/" in my RPM build processing.

> 
> > Also, I’ve received one suggestion to leave the old build system in place, in parallel, but I don’t like that idea. What do you think?
> 
> This is not a bad idea. There are plenty of projects that do this. However, there's a caveat to the notion.
> 
> Having multiple build systems for the sake of having multiple build systems is awkward, a support burden, fragments support efforts, and generally negates any advantages of switching from one to the other. You don't want to do this.
> 
> (Aside: for projects that primarily provide a library, it's also sometimes desirable to provide multiple build systems if those build systems make it easy to add the library as a submodule dependency to another project. It _is_ a support burden, but it might be a worthwhile one. Also: autotools doesn't have that use case.)
> 
> What you probably _do_ want to do, is have one major release after the new build system is introduced, where the old build system is still available, but is deprecated. It might print a warning if you use it, or require passing a configure flag such as --i-cant-use-meson-yet, or just be advised against in the README.
> 
> The idea is that when doing a complex port, you hope it all turns out well, and you give consumers a chance to try it out, but just in case specific consumers hit edge cases that cause issues, people can still use the old build system while those bugs are fixed, and at the same time they get valuable bug fixes from the new release. After the transition period of one release cycle is complete, you delete the old build system and declare victory.

Yes, I understand that, and I believe that's a good approach. But my question was more about your "aside". :)

So when i integrate this in master I will probably leave the current make/autoconf tools in place, but deprecated and no longer supported. :)

**Comment by gonzoleeman** [comment]
Some updates:
- I am converting open-isns to use meson, as the preferred **option**, for now, and leaving but deprecating autotools used there (not yet converted, but soon, I hope)
- The changes in branch _use_meson_v1_ will be redone in a new branch (likely _use_meson_v2_, because I lack imagination)
- I plan on leaving the current open-iscsi build systems (make and autoconf) in place, for now, in case the meson changes have any issues (as is being done in open-isns)

So stay tuned!

Also, see pull request #364 for changes I found while working on this branch that belong in open-iscsi regardless of build system. Those changes are all non-meson related and valuable in their own right. Please comment there if you have any feedback.

Thanks!

**Comment by gonzoleeman** [comment]
@eli-schwartz Have you reviewed the current pull request for use-meson-v2?

**Comment by eli-schwartz** [comment]
I just took a look, thanks for reminding me.

**Comment by gonzoleeman** [comment]
This is done, so closing the issue.
