### ISSUE TITLE
libopeniscsiusr: should we add a symbol version map?

### ISSUE THREAD

**Issue by gonzoleeman** [open-iscsi/open-iscsi#383]
Hi All:

I'm not a library expert, but I have to support libopeniscsiusr. Mostly there isn't much support needed, since it's more or less static these days (not many changes). But recently I ran into an issue I caused when I switched from "make" to "meson" to build open-iscsi.

Originally, when libopeniscsiusr was created at version 0.1.0, the "SONAME" of the library was "libopeniscsiusr.so.0.2.0". (You can read the SONAME with "readelf -a LIBNAME|fgrep SONAME").

As background, the SONAME is supposed to be constant for a library with no API changes, but it is supposed to be updated/changed when the APIs for a library change. The linker assume that if the SONAME is the same, the library is compatible with other libraries with the same SONAME.

So when version 0.2.0 of libopeniscsiusr came alone (with about a dozen new APIs), the SONAME was updated to "libopeniscsiusr.so.0.2.0". In other words, we were telling the linker this version was not compatible with the previous version. Note that this is partly true IMHO. The new library would have indeed worked for older programs, i.e. it was backward compatible. But it was not forward compatible, i.e. new programs would not work with the old library.

All of this is okay. It was a bit of a pain to have to rename the RPM package for the library for a new (compatible) version of the library, but it wasn't too bad.

Then, when I changed the build to use Meson, I missed the fact that the old Make system was setting the SONAME manually, and I just let Meson pick the SONAME for the library. I didn't notice that the SONAME had become "libopeniscsiusr.so.0". This is because the default for meson is to use only the first number of the "version" in the SONAME, i.e. just use the "0" from "0.2.0".

I believe this is actually more correct, i.e. follows general practices for shared libraries, to have the SONAME be "libopeniscsiusr.so.0". A quick check of many shared libraries on my system shows that about 95% of shared libraries name their SONAME this way.

So my hope is to stick with the new SONAME. The "meson" change has been in place a few months now, and I haven't heard any complaints. :) Thought that may be because nobody is using it yet?

One other issue this has brought up, for me, is how to handle future changes to libopeniscsiusr (if any). When we add new APIs, for example, my plan is to leave the SONAME at "libopeniscsiusr.so.0", since the old programs would work with the new library. (I assume we will never change an existing API incompatibly.)

One option suggested is to use symbol versioning. I have looked into this before. Basically, you supply a list of symbols to the linker for each version of the library, and it manages that. You can even handle incompatible API changes this way, by having your library service both the old and the new API (with a little programming sugar).

There's only one problem I see with adding symbol versioning. Ok, maybe two problems. The first problem is that we already control libopeniscsiusr symbol visibility using "export control" in gcc. That means that we put __DLL_EXPORT in front of symbols in the library we want exported, and __DLL_LOCAL for those we do not wish to export:

> #define __DLL_EXPORT    __attribute__ ((visibility ("default")))
> #define __DLL_LOCAL     __attribute__ ((visibility ("hidden")))

The down side is that this only works for newer version of GCC (starting with version 4). Also, this does not allow us to have two versions of the same symbol (only needed if we make an incompatible API change). Note that some experts seem to suggest that this method is better than using a symbol version file, but I must admit it's a touch ugly in the source file.

So I'd love input from others. What do we want to do?

- Leave everything alone. Keep new SONAME, and don't use symbol versioning, since it's not needed
- Keep new SONAME, and add symbol versioning. Only really useful if we make incompatible changes
- Revert the SONAME to "libopeniscsiusr.so.0.2.0", as it was before meson. This means every library update gets a new package name

If you care, let me know. Better to change things now if needed, rather than wait until there's an issue.

**Comment by eli-schwartz** [comment]
Visibility can be used together with version files. The former controls whether a symbol is created, the latter controls the symbol name.

Version files are commonly used for two things (and less commonly used for countless things that aren't under discussion here):
- marking some symbols as `local:` and some as `global:`, the local ones aren't exported. This is similar to visibility, but less optimized, because at link time there's much less you can do. You cannot affect codegen (for code you know doesn't need a symbol), all you can affect is the linkage by *hiding* the symbol.
- grouping symbols in a versioning node

It's redundant to use the former together with visibility. It's useful to use the *latter* together with visibility, assuming you're interested in symbol versioning, because the visibility is more powerful. Yes, that does have a complexity cost, and if you use version files that may be good enough.

**Comment by gonzoleeman** [comment]
@eli-schwartz thank you for your reply -- as usual, very informative. But after reading this a couple of times, I'm still not sure about the bottom line.

For libopeniscsiusr, let's assume it will get very few changes. Given that, my bottom line question is "is it worth it to add symbol versioning on top of the visibility we are already using?".

My main concern is handling what happens the next time we add a few new APIs to the library, i.e. how will it be named/numbered, and will previously-compiled programs (compiled against the previous library) work with the new library.

Adding the symbol versioning is simple enough, but not all platforms support the gcc option to use them, such as OSX and BSD (so I hear). Plus, having the symbol list means we have yet another file to update when adding new APIs, when the idea was to have changes only added in one place. (Okay, two places: a C file and a Header file.)

So I'd rather not add symbol versions unless they actually add something that is valuable to this project, not just valuable theoretically in some cases. :)

**Comment by eli-schwartz** [comment]
It's valuable in the case where you don't add a new symbol -- you modify an existing one to work differently, and newly built programs should always use the new way of doing things, but old binaries that were linked in the past should get access to a "hidden" version of the old way of doing things.

Simply adding new functions doesn't break old programs. You don't need to bump the soname, because the purpose of bumping soname is to force people to relink when old programs linked to the old library would break or malfunction when used with the new library.

(And people don't generally concern themselves with the possibility of *downgrading* the library, but not the program. You cannot solve that problem anyhow. Symbol versioning just means that when upgrading the library *and* you'd usually need to bump the soname, you can instead provide both the old and new library in one file, so to speak.)

**Comment by gonzoleeman** [comment]
I believe I've decided not to add symbol versioning to libopeniscsiusr. It adds a bit of extra work (to set it up and maintain it), and it gives little if no value, especially if we do not plan to make incompatible API changes (and we do not).

**Comment by gonzoleeman** [comment]
I am closing and withdrawing this issue, as I've decided the extra work involved in adding a symbol map is not worth it, given that we already semantically hide all symbols not exported.
