### ISSUE TITLE
displaying and adjusting timeouts

### ISSUE THREAD

**Issue by jstiops** [open-iscsi/open-iscsi#393]
Hi,

I cant seem to get a definite answer on the following.

i have a server currently active with some iSCSI sessions to a target. This was setup with node.session.timeo.replacement_timeout on the default of 120 seconds within iscsid.conf . I want to change that to something like 10 seconds.

questions:
- how would i check the current timeout value bueing used by the sessions? (i dont mean by checking the iscsid.conf....) 
- Will changing the iscsid.conf for node.session.timeo.replacement_timeout take affect after a simple reboot ?

i read somewhere a re-login is needed for this timeoutto take affect, but i dont know for sure if a reboot would do this relogin.
That's why i also want to know what the best way is to check the current timeout value used for (e.g.) node.session.timeo.replacement_timeout

**Comment by gonzoleeman** [comment]
I assume you're using the node database to log into targets, since you mentioned setting node.session values.

The value you set for this timeout goes into the node database for the node (target) in question. So when you say:

`# iscsiadm -m node --op update --name node.session.timeo.replacement_timeout --value 10`

It changes the value in the node database entry (a file, usually in /etc/iscsi/nodes or /var/lib/iscsi/nodes). That value only takes effect when you connect to the target. So changing the value, logging out of the target (ending that session), then logging back in (creating a new session) should use the new timeout value you've set. So when you reboot, of course that disconnects from all targets (before your system goes down), then reconnects to targets when your system comes back up, assuming you have your system set up for automatic login to targets with node.startup=auto.

To check the current running timeout value, try:

`# iscsiadm -m session -P3`

which would print the values for all sessions. Use "-s <session-id>" to check just one session. To check the current node timeout value:

`# iscsiadm -m node -T <target-name> --op show --name node.session.timeo.replacement_timeout `

Which would check for just one target. Leave off the "-T <target-name>" to check all of them.

**Comment by jstiops** [comment]
Thanks alot! All clear now

**Comment by gonzoleeman** [comment]
Closing issue as resolved. If you still have questions, please re-open or open a new issue.
