### ISSUE TITLE
iscsiadm logout fail

### ISSUE THREAD

**Issue by happyzyz** [open-iscsi/open-iscsi#402]
![image](https://user-images.githubusercontent.com/123857360/223982560-7c9f728f-65b8-45f0-b6d1-392939482f83.png)
![image](https://user-images.githubusercontent.com/123857360/223982829-369580c6-6c0f-48a1-80f4-2954eb144439.png)rpp
![image](https://user-images.githubusercontent.com/123857360/223983058-48cc5c4c-8f04-4d21-b148-f47896ed6eb0.png)
iscis
Hi iscsi experts,
I am encountering some failures of iscsiadm
Any feedback will be appreciated. Thanks!

**Comment by gonzoleeman** [comment]
Looks like there are several issues here. What distro are you using? What is the version of iscsid/iscsiadm?

As far as your iscsid.service status: looks like it's having issues connecting to your target. It looks like your target may have not set permissions correctly. What software are you using for your target? (Or is it a hardware target?)

It _looks_ like (from this limited information) that logging into the target fails, but then the kernel still thinks there is a session?

You need to be able to manually:
- perform discovery, to make sure you can reach your target (it looks like that has been done, at some point, since you have a Node DB record)
- log into the target, and
- log out of the target
If there are "orphaned sessions", then rebooting will clear them up. Then, with a clean system, go through the above steps and show me the results.

You can list sessions with "iscsiadm -m session", so please do that.

**Comment by gonzoleeman** [comment]
> The target is destroyed

If, by this, you mean that the target was working fine before you ran iscsiadm, and then the target "went away" (somehow) after you tried to run iscsiadm, then it sounds like your target code has issues. Again, what type of target are you using?

**Comment by happyzyz** [comment]
Thank you for your reply, but the environment is gone, and I can't show you any information
The target is ISCSI target based on spdk(v20.10).
The target is destroyed mean that i destroy the target before i ran iscsiadm.

**Comment by gonzoleeman** [comment]
Well if you destroyed the target before you ran iscsiadm, what did you expect? If the target is present during discovery, a Node DB entry is created. Then when you tell it to log into the target represented by that node, it fails. As expected.

Sounds like this issue can be closed?

**Comment by happyzyz** [comment]
YES
