### ISSUE TITLE
is there any plan to support mac os apple silicon in the future

### ISSUE THREAD

**Issue by EvilDragonFly** [open-iscsi/open-iscsi#434]

**Comment by gonzoleeman** [comment]
What does this mean? How is Mac OS Silicon not supported? If you mean OSX, then support is unlikely since it's not very Unix-like.

**Comment by gonzoleeman** [comment]
No reply in two months, so closing. If you meant MacOS, no. If you meant the CPU, it's already supported for Linux.

**Comment by amnesia0287** [comment]
> What does this mean? How is Mac OS Silicon not supported? If you mean OSX, then support is unlikely since it's not very Unix-like.

Genuinely curious about this response since macOS is certified unix: https://www.opengroup.org/openbrand/register/

It’s Linux that doesn’t comply lol. 

Any idea where the kernel source for open-ISCSI lives these days if I wanted to poke around and see if I could make it work on Mac? lol.

**Comment by gonzoleeman** [comment]
The MacOS kernel is nothing like the Linux kernel. The open-iscsi project started with both the kernel and user parts as part of their project, but @mikechristie was instrumental (I believe) in making the iSCSI initiator code largely kernel based. Only configuration and error handling is done by the user-land code. The project is much better able to handle kernel changes now, since in-kernel drivers get updated when the kernel changes, plus they are exposed to a wider audience, so they can get more bug fixes and enhancements.

The kernel sources for the iscsi initiator are, not surprisingly, in the Linux source tree. I believe if you look in the MAINTAINERS file you will see my name, along with open-iscsi co-maintainer Chris Leech, and Mike Christie (the previous project maintainer, and still an expert). That file also lists the parts of the kernel where iSCSI lives.
