### ISSUE TITLE
Parallel Requests

### ISSUE THREAD

**Issue by neetz07** [open-iscsi/open-iscsi#456]
Hi, 
I have 2 questions
1. Does iscsiadm support parallel logins to unique volumes? i.e if i have 5 volumes/targets, can i connect to them parallely that includes adding to node db and then logging. 
2. Does iscsiadm support connecting to same target with multiple sessions parallely? i see some issues mentioned here that it's not supported -> https://github.com/open-iscsi/open-iscsi/issues/302

**Comment by gonzoleeman** [comment]
On Jun 19, 2024, at 9:10 AM, Neetish Bhat ***@***.***> wrote:
> 
> 
> Hi,
> I have 2 questions
> 
> Does iscsiadm support parallel logins to unique volumes? i.e if i have 5 volumes/targets, can i connect to them parallely that includes adding to node db and then logging.
> Does iscsiadm support connecting to same target with multiple sessions parallely? i see some issues mentioned here that it's not supported -> #302 <https://github.com/open-iscsi/open-iscsi/issues/302>
No, and no. :)

The iscsiadm command should be able to handle “parallel” request, but it will do so with a big lock around the Node Database (which is, in fact, a bunch of directories and files).

So that kind of answers both of your questions.

You can login to multiple targets without waiting for each one to respond. I believe it’s the “-W” option. In testing, this seemed to make it a little faster than waiting for each response, with multiple targets. Using this, it’s up to the caller to detect success (a login) or failure.

Could the database be modernized a parallelized? Right now the root user can accidently screw up the “database”, or modify it (e.g. using “vi”). There currently aren’t any checksums, either. But short of switching to an actual database, it’d be difficult to add parallelism.

— 
Lee Duncan

**Comment by gonzoleeman** [comment]
If there's no more to discuss I will close this soon.

**Comment by Neetz** [comment]
Hi, 
Thank you for explanation. Understood.

**Comment by Neetz** [comment]
We can close this issue

**Comment by gonzoleeman** [comment]
closing.
